### ISSUE TITLE
Multi-language e.g. English, French, Spanish, Dutch, etc....

### ISSUE THREAD

**Issue by sanyaade-speechtools** [fontainejp/blocklino#4]
Hi I will like to translate this kit into English.
How can we translate this kit into other languages?
Please explain?

Hear from you soon!

God blesses!!!

Best regards,
Sanyaade

**Comment by fontainejp** [comment]
Hi,
It's more easy to translate the app now.
Go to www\lang and translate the files Arduino_en.js, Blockly_en.js and msg_en.js in english
It's about 80% of works but there are few things in other files (html and js) because it's to difficult for me to put them in the same files.
For another language spanish for example :
 - copy / paste *_en.js 
 - rename  *_es.js
 - edit code.js and add at the end line 4  'es': 'Spanish',
Think it's help you
JP
